package com.ezone.ezproject.dal.entity;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Database Table Remarks:
 *   附件
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table attachment
 * @Author mybatis-code-generator
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class Attachment implements Serializable {
    @ApiModelProperty(value = "附件id")
    private Long id;

    @ApiModelProperty(value = "附件文件名")
    private String fileName;

    @ApiModelProperty(value = "附件存储路径")
    private String storagePath;

    @ApiModelProperty(value = "描述")
    private String description;

    @ApiModelProperty(value = "上传时间")
    private Date uploadTime;

    @ApiModelProperty(value = "上传人")
    private String uploadUser;

    @ApiModelProperty(value = "文件类型")
    private String contentType;

    private static final long serialVersionUID = 1L;
}