package com.ezone.ezproject.dal.entity;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Database Table Remarks:
 *   卡片关联关系
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table card_relate_rel
 * @Author mybatis-code-generator
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class CardRelateRel implements Serializable {
    @ApiModelProperty(value = "id")
    private Long id;

    @ApiModelProperty(value = "卡片id")
    private Long cardId;

    @ApiModelProperty(value = "关联id")
    private Long relatedCardId;

    private static final long serialVersionUID = 1L;
}