package com.ezone.ezproject.dal.entity;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Database Table Remarks:
 *   卡片关联wiki page
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table card_wiki_page_rel
 * @Author mybatis-code-generator
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class CardWikiPageRel implements Serializable {
    @ApiModelProperty(value = "id")
    private Long id;

    @ApiModelProperty(value = "卡片ID")
    private Long cardId;

    @ApiModelProperty(value = "page ID")
    private Long pageId;

    @ApiModelProperty(value = "添加人")
    private String createUser;

    @ApiModelProperty(value = "添加时间")
    private Date createTime;

    @ApiModelProperty(value = "wiki space Id")
    private Long wikiSpaceId;

    private static final long serialVersionUID = 1L;
}