package com.ezone.ezproject.dal.entity;

import java.util.ArrayList;
import java.util.List;

public class CardExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    public CardExample() {
        oredCriteria = new ArrayList<>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table card
     * @Author mybatis-code-generator
     *
     * @mbg.generated Mon Nov 14 15:37:25 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("`project_id` is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("`project_id` is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Long value) {
            addCriterion("`project_id` =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Long value) {
            addCriterion("`project_id` <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Long value) {
            addCriterion("`project_id` >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`project_id` >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Long value) {
            addCriterion("`project_id` <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Long value) {
            addCriterion("`project_id` <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Long> values) {
            addCriterion("`project_id` in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Long> values) {
            addCriterion("`project_id` not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Long value1, Long value2) {
            addCriterion("`project_id` between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Long value1, Long value2) {
            addCriterion("`project_id` not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectKeyIsNull() {
            addCriterion("`project_key` is null");
            return (Criteria) this;
        }

        public Criteria andProjectKeyIsNotNull() {
            addCriterion("`project_key` is not null");
            return (Criteria) this;
        }

        public Criteria andProjectKeyEqualTo(String value) {
            addCriterion("`project_key` =", value, "projectKey");
            return (Criteria) this;
        }

        public Criteria andProjectKeyNotEqualTo(String value) {
            addCriterion("`project_key` <>", value, "projectKey");
            return (Criteria) this;
        }

        public Criteria andProjectKeyGreaterThan(String value) {
            addCriterion("`project_key` >", value, "projectKey");
            return (Criteria) this;
        }

        public Criteria andProjectKeyGreaterThanOrEqualTo(String value) {
            addCriterion("`project_key` >=", value, "projectKey");
            return (Criteria) this;
        }

        public Criteria andProjectKeyLessThan(String value) {
            addCriterion("`project_key` <", value, "projectKey");
            return (Criteria) this;
        }

        public Criteria andProjectKeyLessThanOrEqualTo(String value) {
            addCriterion("`project_key` <=", value, "projectKey");
            return (Criteria) this;
        }

        public Criteria andProjectKeyLike(String value) {
            addCriterion("`project_key` like", value, "projectKey");
            return (Criteria) this;
        }

        public Criteria andProjectKeyNotLike(String value) {
            addCriterion("`project_key` not like", value, "projectKey");
            return (Criteria) this;
        }

        public Criteria andProjectKeyIn(List<String> values) {
            addCriterion("`project_key` in", values, "projectKey");
            return (Criteria) this;
        }

        public Criteria andProjectKeyNotIn(List<String> values) {
            addCriterion("`project_key` not in", values, "projectKey");
            return (Criteria) this;
        }

        public Criteria andProjectKeyBetween(String value1, String value2) {
            addCriterion("`project_key` between", value1, value2, "projectKey");
            return (Criteria) this;
        }

        public Criteria andProjectKeyNotBetween(String value1, String value2) {
            addCriterion("`project_key` not between", value1, value2, "projectKey");
            return (Criteria) this;
        }

        public Criteria andSeqNumIsNull() {
            addCriterion("`seq_num` is null");
            return (Criteria) this;
        }

        public Criteria andSeqNumIsNotNull() {
            addCriterion("`seq_num` is not null");
            return (Criteria) this;
        }

        public Criteria andSeqNumEqualTo(Long value) {
            addCriterion("`seq_num` =", value, "seqNum");
            return (Criteria) this;
        }

        public Criteria andSeqNumNotEqualTo(Long value) {
            addCriterion("`seq_num` <>", value, "seqNum");
            return (Criteria) this;
        }

        public Criteria andSeqNumGreaterThan(Long value) {
            addCriterion("`seq_num` >", value, "seqNum");
            return (Criteria) this;
        }

        public Criteria andSeqNumGreaterThanOrEqualTo(Long value) {
            addCriterion("`seq_num` >=", value, "seqNum");
            return (Criteria) this;
        }

        public Criteria andSeqNumLessThan(Long value) {
            addCriterion("`seq_num` <", value, "seqNum");
            return (Criteria) this;
        }

        public Criteria andSeqNumLessThanOrEqualTo(Long value) {
            addCriterion("`seq_num` <=", value, "seqNum");
            return (Criteria) this;
        }

        public Criteria andSeqNumIn(List<Long> values) {
            addCriterion("`seq_num` in", values, "seqNum");
            return (Criteria) this;
        }

        public Criteria andSeqNumNotIn(List<Long> values) {
            addCriterion("`seq_num` not in", values, "seqNum");
            return (Criteria) this;
        }

        public Criteria andSeqNumBetween(Long value1, Long value2) {
            addCriterion("`seq_num` between", value1, value2, "seqNum");
            return (Criteria) this;
        }

        public Criteria andSeqNumNotBetween(Long value1, Long value2) {
            addCriterion("`seq_num` not between", value1, value2, "seqNum");
            return (Criteria) this;
        }

        public Criteria andPlanIdIsNull() {
            addCriterion("`plan_id` is null");
            return (Criteria) this;
        }

        public Criteria andPlanIdIsNotNull() {
            addCriterion("`plan_id` is not null");
            return (Criteria) this;
        }

        public Criteria andPlanIdEqualTo(Long value) {
            addCriterion("`plan_id` =", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdNotEqualTo(Long value) {
            addCriterion("`plan_id` <>", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdGreaterThan(Long value) {
            addCriterion("`plan_id` >", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`plan_id` >=", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdLessThan(Long value) {
            addCriterion("`plan_id` <", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdLessThanOrEqualTo(Long value) {
            addCriterion("`plan_id` <=", value, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdIn(List<Long> values) {
            addCriterion("`plan_id` in", values, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdNotIn(List<Long> values) {
            addCriterion("`plan_id` not in", values, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdBetween(Long value1, Long value2) {
            addCriterion("`plan_id` between", value1, value2, "planId");
            return (Criteria) this;
        }

        public Criteria andPlanIdNotBetween(Long value1, Long value2) {
            addCriterion("`plan_id` not between", value1, value2, "planId");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("`parent_id` is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("`parent_id` is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(Long value) {
            addCriterion("`parent_id` =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(Long value) {
            addCriterion("`parent_id` <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(Long value) {
            addCriterion("`parent_id` >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`parent_id` >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(Long value) {
            addCriterion("`parent_id` <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(Long value) {
            addCriterion("`parent_id` <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<Long> values) {
            addCriterion("`parent_id` in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<Long> values) {
            addCriterion("`parent_id` not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(Long value1, Long value2) {
            addCriterion("`parent_id` between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(Long value1, Long value2) {
            addCriterion("`parent_id` not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andAncestorIdIsNull() {
            addCriterion("`ancestor_id` is null");
            return (Criteria) this;
        }

        public Criteria andAncestorIdIsNotNull() {
            addCriterion("`ancestor_id` is not null");
            return (Criteria) this;
        }

        public Criteria andAncestorIdEqualTo(Long value) {
            addCriterion("`ancestor_id` =", value, "ancestorId");
            return (Criteria) this;
        }

        public Criteria andAncestorIdNotEqualTo(Long value) {
            addCriterion("`ancestor_id` <>", value, "ancestorId");
            return (Criteria) this;
        }

        public Criteria andAncestorIdGreaterThan(Long value) {
            addCriterion("`ancestor_id` >", value, "ancestorId");
            return (Criteria) this;
        }

        public Criteria andAncestorIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`ancestor_id` >=", value, "ancestorId");
            return (Criteria) this;
        }

        public Criteria andAncestorIdLessThan(Long value) {
            addCriterion("`ancestor_id` <", value, "ancestorId");
            return (Criteria) this;
        }

        public Criteria andAncestorIdLessThanOrEqualTo(Long value) {
            addCriterion("`ancestor_id` <=", value, "ancestorId");
            return (Criteria) this;
        }

        public Criteria andAncestorIdIn(List<Long> values) {
            addCriterion("`ancestor_id` in", values, "ancestorId");
            return (Criteria) this;
        }

        public Criteria andAncestorIdNotIn(List<Long> values) {
            addCriterion("`ancestor_id` not in", values, "ancestorId");
            return (Criteria) this;
        }

        public Criteria andAncestorIdBetween(Long value1, Long value2) {
            addCriterion("`ancestor_id` between", value1, value2, "ancestorId");
            return (Criteria) this;
        }

        public Criteria andAncestorIdNotBetween(Long value1, Long value2) {
            addCriterion("`ancestor_id` not between", value1, value2, "ancestorId");
            return (Criteria) this;
        }

        public Criteria andRankIsNull() {
            addCriterion("`rank` is null");
            return (Criteria) this;
        }

        public Criteria andRankIsNotNull() {
            addCriterion("`rank` is not null");
            return (Criteria) this;
        }

        public Criteria andRankEqualTo(String value) {
            addCriterion("`rank` =", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotEqualTo(String value) {
            addCriterion("`rank` <>", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThan(String value) {
            addCriterion("`rank` >", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThanOrEqualTo(String value) {
            addCriterion("`rank` >=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThan(String value) {
            addCriterion("`rank` <", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThanOrEqualTo(String value) {
            addCriterion("`rank` <=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLike(String value) {
            addCriterion("`rank` like", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotLike(String value) {
            addCriterion("`rank` not like", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankIn(List<String> values) {
            addCriterion("`rank` in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotIn(List<String> values) {
            addCriterion("`rank` not in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankBetween(String value1, String value2) {
            addCriterion("`rank` between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotBetween(String value1, String value2) {
            addCriterion("`rank` not between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("`company_id` is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("`company_id` is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(Long value) {
            addCriterion("`company_id` =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(Long value) {
            addCriterion("`company_id` <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(Long value) {
            addCriterion("`company_id` >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`company_id` >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(Long value) {
            addCriterion("`company_id` <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(Long value) {
            addCriterion("`company_id` <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<Long> values) {
            addCriterion("`company_id` in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<Long> values) {
            addCriterion("`company_id` not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(Long value1, Long value2) {
            addCriterion("`company_id` between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(Long value1, Long value2) {
            addCriterion("`company_id` not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("`deleted` is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("`deleted` is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Boolean value) {
            addCriterion("`deleted` =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Boolean value) {
            addCriterion("`deleted` <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Boolean value) {
            addCriterion("`deleted` >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("`deleted` >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Boolean value) {
            addCriterion("`deleted` <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("`deleted` <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Boolean> values) {
            addCriterion("`deleted` in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Boolean> values) {
            addCriterion("`deleted` not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("`deleted` between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("`deleted` not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andMaxCommentSeqNumIsNull() {
            addCriterion("`max_comment_seq_num` is null");
            return (Criteria) this;
        }

        public Criteria andMaxCommentSeqNumIsNotNull() {
            addCriterion("`max_comment_seq_num` is not null");
            return (Criteria) this;
        }

        public Criteria andMaxCommentSeqNumEqualTo(Long value) {
            addCriterion("`max_comment_seq_num` =", value, "maxCommentSeqNum");
            return (Criteria) this;
        }

        public Criteria andMaxCommentSeqNumNotEqualTo(Long value) {
            addCriterion("`max_comment_seq_num` <>", value, "maxCommentSeqNum");
            return (Criteria) this;
        }

        public Criteria andMaxCommentSeqNumGreaterThan(Long value) {
            addCriterion("`max_comment_seq_num` >", value, "maxCommentSeqNum");
            return (Criteria) this;
        }

        public Criteria andMaxCommentSeqNumGreaterThanOrEqualTo(Long value) {
            addCriterion("`max_comment_seq_num` >=", value, "maxCommentSeqNum");
            return (Criteria) this;
        }

        public Criteria andMaxCommentSeqNumLessThan(Long value) {
            addCriterion("`max_comment_seq_num` <", value, "maxCommentSeqNum");
            return (Criteria) this;
        }

        public Criteria andMaxCommentSeqNumLessThanOrEqualTo(Long value) {
            addCriterion("`max_comment_seq_num` <=", value, "maxCommentSeqNum");
            return (Criteria) this;
        }

        public Criteria andMaxCommentSeqNumIn(List<Long> values) {
            addCriterion("`max_comment_seq_num` in", values, "maxCommentSeqNum");
            return (Criteria) this;
        }

        public Criteria andMaxCommentSeqNumNotIn(List<Long> values) {
            addCriterion("`max_comment_seq_num` not in", values, "maxCommentSeqNum");
            return (Criteria) this;
        }

        public Criteria andMaxCommentSeqNumBetween(Long value1, Long value2) {
            addCriterion("`max_comment_seq_num` between", value1, value2, "maxCommentSeqNum");
            return (Criteria) this;
        }

        public Criteria andMaxCommentSeqNumNotBetween(Long value1, Long value2) {
            addCriterion("`max_comment_seq_num` not between", value1, value2, "maxCommentSeqNum");
            return (Criteria) this;
        }

        public Criteria andStoryMapNodeIdIsNull() {
            addCriterion("`story_map_node_id` is null");
            return (Criteria) this;
        }

        public Criteria andStoryMapNodeIdIsNotNull() {
            addCriterion("`story_map_node_id` is not null");
            return (Criteria) this;
        }

        public Criteria andStoryMapNodeIdEqualTo(Long value) {
            addCriterion("`story_map_node_id` =", value, "storyMapNodeId");
            return (Criteria) this;
        }

        public Criteria andStoryMapNodeIdNotEqualTo(Long value) {
            addCriterion("`story_map_node_id` <>", value, "storyMapNodeId");
            return (Criteria) this;
        }

        public Criteria andStoryMapNodeIdGreaterThan(Long value) {
            addCriterion("`story_map_node_id` >", value, "storyMapNodeId");
            return (Criteria) this;
        }

        public Criteria andStoryMapNodeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`story_map_node_id` >=", value, "storyMapNodeId");
            return (Criteria) this;
        }

        public Criteria andStoryMapNodeIdLessThan(Long value) {
            addCriterion("`story_map_node_id` <", value, "storyMapNodeId");
            return (Criteria) this;
        }

        public Criteria andStoryMapNodeIdLessThanOrEqualTo(Long value) {
            addCriterion("`story_map_node_id` <=", value, "storyMapNodeId");
            return (Criteria) this;
        }

        public Criteria andStoryMapNodeIdIn(List<Long> values) {
            addCriterion("`story_map_node_id` in", values, "storyMapNodeId");
            return (Criteria) this;
        }

        public Criteria andStoryMapNodeIdNotIn(List<Long> values) {
            addCriterion("`story_map_node_id` not in", values, "storyMapNodeId");
            return (Criteria) this;
        }

        public Criteria andStoryMapNodeIdBetween(Long value1, Long value2) {
            addCriterion("`story_map_node_id` between", value1, value2, "storyMapNodeId");
            return (Criteria) this;
        }

        public Criteria andStoryMapNodeIdNotBetween(Long value1, Long value2) {
            addCriterion("`story_map_node_id` not between", value1, value2, "storyMapNodeId");
            return (Criteria) this;
        }

        public Criteria andLatestEventIdIsNull() {
            addCriterion("`latest_event_id` is null");
            return (Criteria) this;
        }

        public Criteria andLatestEventIdIsNotNull() {
            addCriterion("`latest_event_id` is not null");
            return (Criteria) this;
        }

        public Criteria andLatestEventIdEqualTo(Long value) {
            addCriterion("`latest_event_id` =", value, "latestEventId");
            return (Criteria) this;
        }

        public Criteria andLatestEventIdNotEqualTo(Long value) {
            addCriterion("`latest_event_id` <>", value, "latestEventId");
            return (Criteria) this;
        }

        public Criteria andLatestEventIdGreaterThan(Long value) {
            addCriterion("`latest_event_id` >", value, "latestEventId");
            return (Criteria) this;
        }

        public Criteria andLatestEventIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`latest_event_id` >=", value, "latestEventId");
            return (Criteria) this;
        }

        public Criteria andLatestEventIdLessThan(Long value) {
            addCriterion("`latest_event_id` <", value, "latestEventId");
            return (Criteria) this;
        }

        public Criteria andLatestEventIdLessThanOrEqualTo(Long value) {
            addCriterion("`latest_event_id` <=", value, "latestEventId");
            return (Criteria) this;
        }

        public Criteria andLatestEventIdIn(List<Long> values) {
            addCriterion("`latest_event_id` in", values, "latestEventId");
            return (Criteria) this;
        }

        public Criteria andLatestEventIdNotIn(List<Long> values) {
            addCriterion("`latest_event_id` not in", values, "latestEventId");
            return (Criteria) this;
        }

        public Criteria andLatestEventIdBetween(Long value1, Long value2) {
            addCriterion("`latest_event_id` between", value1, value2, "latestEventId");
            return (Criteria) this;
        }

        public Criteria andLatestEventIdNotBetween(Long value1, Long value2) {
            addCriterion("`latest_event_id` not between", value1, value2, "latestEventId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table card
     * @Author mybatis-code-generator
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 14 15:37:25 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table card
     * @Author mybatis-code-generator
     *
     * @mbg.generated Mon Nov 14 15:37:25 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}