package com.ezone.ezproject.dal.entity;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.io.Serializable;

/**
 * Database Table Remarks:
 * 卡片通知计划
 * <p>
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table card_alarm_notice_plan
 *
 * @Author mybatis-code-generator
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class CardAlarmNoticePlan implements Serializable {
    @ApiModelProperty(value = "附件id")
    private Long id;

    @ApiModelProperty(value = "项目ID")
    private Long projectId;

    @ApiModelProperty(value = "卡片ID")
    private Long cardId;

    @ApiModelProperty(value = "触发的预警配置ID")
    private Long alarmId;

    @ApiModelProperty(value = "预警触发通知的时间戳（精确到分）")
    private Integer timestampMinute;

    @ApiModelProperty(value = "发送标记：0-未发送，1-已发送")
    private Integer sendFlag;

    private static final long serialVersionUID = 1L;
}