package com.ezone.ezproject.dal.entity;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Database Table Remarks:
 *   卡片
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table card
 * @Author mybatis-code-generator
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class Card implements Serializable {
    @ApiModelProperty(value = "卡片id")
    private Long id;

    @ApiModelProperty(value = "所属项目ID")
    private Long projectId;

    @ApiModelProperty(value = "所属项目标识")
    private String projectKey;

    @ApiModelProperty(value = "卡片编号")
    private Long seqNum;

    @ApiModelProperty(value = "绑定计划ID")
    private Long planId;

    @ApiModelProperty(value = "父卡片ID")
    private Long parentId;

    @ApiModelProperty(value = "祖先卡片ID")
    private Long ancestorId;

    @ApiModelProperty(value = "优先级排序地位，字典序")
    private String rank;

    @ApiModelProperty(value = "公司")
    private Long companyId;

    @ApiModelProperty(value = "逻辑删除")
    private Boolean deleted;

    @ApiModelProperty(value = "评论最大楼层")
    private Long maxCommentSeqNum;

    @ApiModelProperty(value = "故事地图分类节点ID")
    private Long storyMapNodeId;

    @ApiModelProperty(value = "最近卡片变更事件ID")
    private Long latestEventId;

    private static final long serialVersionUID = 1L;
}