package com.ezone.ezproject.dal.entity;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Database Table Remarks:
 *   计划的里程碑目标
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table plan_goal
 * @Author mybatis-code-generator
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class PlanGoal implements Serializable {
    @ApiModelProperty(value = "卡片id")
    private Long id;

    @ApiModelProperty(value = "绑定计划ID")
    private Long planId;

    @ApiModelProperty(value = "负责人")
    private String owner;

    @ApiModelProperty(value = "状态")
    private String status;

    @ApiModelProperty(value = "目标描述")
    private String description;

    @ApiModelProperty(value = "创建时间")
    private Date createTime;

    @ApiModelProperty(value = "创建人")
    private String createUser;

    @ApiModelProperty(value = "最近修改时间")
    private Date lastModifyTime;

    @ApiModelProperty(value = "最近修改人")
    private String lastModifyUser;

    private static final long serialVersionUID = 1L;
}