package com.ezone.ezproject.dal.entity;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Database Table Remarks:
 *   计划
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table plan
 * @Author mybatis-code-generator
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class Plan implements Serializable {
    @ApiModelProperty(value = "计划id")
    private Long id;

    @ApiModelProperty(value = "计划名")
    private String name;

    @ApiModelProperty(value = "所属项目ID")
    private Long projectId;

    @ApiModelProperty(value = "父计划ID")
    private Long parentId;

    @ApiModelProperty(value = "祖先计划ID")
    private Long ancestorId;

    @ApiModelProperty(value = "开始时间")
    private Date startTime;

    @ApiModelProperty(value = "结束时间")
    private Date endTime;

    @ApiModelProperty(value = "活跃或已归档")
    private Boolean isActive;

    @ApiModelProperty(value = "创建时间")
    private Date createTime;

    @ApiModelProperty(value = "创建人")
    private String createUser;

    @ApiModelProperty(value = "最近修改时间")
    private Date lastModifyTime;

    @ApiModelProperty(value = "最近修改人")
    private String lastModifyUser;

    @ApiModelProperty(value = "交付线-含义同卡片排序字段")
    private String deliverLineRank;

    private static final long serialVersionUID = 1L;
}