package com.ezone.ezproject.dal.entity;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Database Table Remarks:
 *   项目集
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table portfolio
 * @Author mybatis-code-generator
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class Portfolio implements Serializable {
    @ApiModelProperty(value = "主键")
    private Long id;

    @ApiModelProperty(value = "公司ID")
    private Long companyId;

    @ApiModelProperty(value = "开始时间")
    private Date startDate;

    @ApiModelProperty(value = "结束时间")
    private Date endDate;

    @ApiModelProperty(value = "父项目集ID")
    private Long parentId;

    @ApiModelProperty(value = "祖先项目集ID")
    private Long ancestorId;

    @ApiModelProperty(value = "项目集路径")
    private String path;

    @ApiModelProperty(value = "项目集名称")
    private String name;

    private static final long serialVersionUID = 1L;
}