package com.ezone.ezproject.dal.entity;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Database Table Remarks:
 *   报表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table portfolio_chart
 * @Author mybatis-code-generator
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class PortfolioChart implements Serializable {
    @ApiModelProperty(value = "报表id")
    private Long id;

    @ApiModelProperty(value = "项目集ID")
    private Long portfolioId;

    @ApiModelProperty(value = "标题")
    private String title;

    @ApiModelProperty(value = "chart类型")
    private String chartType;

    @ApiModelProperty(value = "创建时间")
    private Date createTime;

    @ApiModelProperty(value = "创建人")
    private String createUser;

    @ApiModelProperty(value = "最近修改时间")
    private Date lastModifyTime;

    @ApiModelProperty(value = "最近修改人")
    private String lastModifyUser;

    @ApiModelProperty(value = "顺序编号")
    private Integer seqNum;

    private static final long serialVersionUID = 1L;
}