package com.ezone.ezproject.dal.entity;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Database Table Remarks:
 *   项目版本关联代码库版本
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table product_version_relate_repo_version
 * @Author mybatis-code-generator
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class ProductVersionRelateRepoVersion implements Serializable {
    @ApiModelProperty(value = "id")
    private Long id;

    @ApiModelProperty(value = "项目版本id")
    private Long versionId;

    @ApiModelProperty(value = "代码库id")
    private Long repoId;

    @ApiModelProperty(value = "代码库版本tagId")
    private Long codeTagId;

    @ApiModelProperty(value = "代码库版本tag创建时间")
    private Long codeTagTime;

    @ApiModelProperty(value = "创建人")
    private String createUser;

    @ApiModelProperty(value = "创建时间")
    private Date createTime;

    private static final long serialVersionUID = 1L;
}