package com.ezone.ezproject.dal.entity;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Database Table Remarks:
 *   收藏
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table project_favourite
 * @Author mybatis-code-generator
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class ProjectFavourite implements Serializable {
    @ApiModelProperty(value = "ID")
    private Long id;

    @ApiModelProperty(value = "人")
    private String user;

    @ApiModelProperty(value = "时间")
    private Date time;

    @ApiModelProperty(value = "公司")
    private Long companyId;

    @ApiModelProperty(value = "项目ID")
    private Long projectId;

    private static final long serialVersionUID = 1L;
}