package com.ezone.ezproject.dal.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProjectExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    public ProjectExample() {
        oredCriteria = new ArrayList<>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project
     * @Author mybatis-code-generator
     *
     * @mbg.generated Fri Feb 10 17:22:46 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("`company_id` is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("`company_id` is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(Long value) {
            addCriterion("`company_id` =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(Long value) {
            addCriterion("`company_id` <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(Long value) {
            addCriterion("`company_id` >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`company_id` >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(Long value) {
            addCriterion("`company_id` <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(Long value) {
            addCriterion("`company_id` <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<Long> values) {
            addCriterion("`company_id` in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<Long> values) {
            addCriterion("`company_id` not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(Long value1, Long value2) {
            addCriterion("`company_id` between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(Long value1, Long value2) {
            addCriterion("`company_id` not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("`description` is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("`description` is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("`description` =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("`description` <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("`description` >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("`description` >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("`description` <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("`description` <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("`description` like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("`description` not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("`description` in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("`description` not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("`description` between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("`description` not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andKeyIsNull() {
            addCriterion("`key` is null");
            return (Criteria) this;
        }

        public Criteria andKeyIsNotNull() {
            addCriterion("`key` is not null");
            return (Criteria) this;
        }

        public Criteria andKeyEqualTo(String value) {
            addCriterion("`key` =", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyNotEqualTo(String value) {
            addCriterion("`key` <>", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyGreaterThan(String value) {
            addCriterion("`key` >", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyGreaterThanOrEqualTo(String value) {
            addCriterion("`key` >=", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyLessThan(String value) {
            addCriterion("`key` <", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyLessThanOrEqualTo(String value) {
            addCriterion("`key` <=", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyLike(String value) {
            addCriterion("`key` like", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyNotLike(String value) {
            addCriterion("`key` not like", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyIn(List<String> values) {
            addCriterion("`key` in", values, "key");
            return (Criteria) this;
        }

        public Criteria andKeyNotIn(List<String> values) {
            addCriterion("`key` not in", values, "key");
            return (Criteria) this;
        }

        public Criteria andKeyBetween(String value1, String value2) {
            addCriterion("`key` between", value1, value2, "key");
            return (Criteria) this;
        }

        public Criteria andKeyNotBetween(String value1, String value2) {
            addCriterion("`key` not between", value1, value2, "key");
            return (Criteria) this;
        }

        public Criteria andMaxSeqNumIsNull() {
            addCriterion("`max_seq_num` is null");
            return (Criteria) this;
        }

        public Criteria andMaxSeqNumIsNotNull() {
            addCriterion("`max_seq_num` is not null");
            return (Criteria) this;
        }

        public Criteria andMaxSeqNumEqualTo(Long value) {
            addCriterion("`max_seq_num` =", value, "maxSeqNum");
            return (Criteria) this;
        }

        public Criteria andMaxSeqNumNotEqualTo(Long value) {
            addCriterion("`max_seq_num` <>", value, "maxSeqNum");
            return (Criteria) this;
        }

        public Criteria andMaxSeqNumGreaterThan(Long value) {
            addCriterion("`max_seq_num` >", value, "maxSeqNum");
            return (Criteria) this;
        }

        public Criteria andMaxSeqNumGreaterThanOrEqualTo(Long value) {
            addCriterion("`max_seq_num` >=", value, "maxSeqNum");
            return (Criteria) this;
        }

        public Criteria andMaxSeqNumLessThan(Long value) {
            addCriterion("`max_seq_num` <", value, "maxSeqNum");
            return (Criteria) this;
        }

        public Criteria andMaxSeqNumLessThanOrEqualTo(Long value) {
            addCriterion("`max_seq_num` <=", value, "maxSeqNum");
            return (Criteria) this;
        }

        public Criteria andMaxSeqNumIn(List<Long> values) {
            addCriterion("`max_seq_num` in", values, "maxSeqNum");
            return (Criteria) this;
        }

        public Criteria andMaxSeqNumNotIn(List<Long> values) {
            addCriterion("`max_seq_num` not in", values, "maxSeqNum");
            return (Criteria) this;
        }

        public Criteria andMaxSeqNumBetween(Long value1, Long value2) {
            addCriterion("`max_seq_num` between", value1, value2, "maxSeqNum");
            return (Criteria) this;
        }

        public Criteria andMaxSeqNumNotBetween(Long value1, Long value2) {
            addCriterion("`max_seq_num` not between", value1, value2, "maxSeqNum");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("`create_time` is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("`create_time` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("`create_time` =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("`create_time` <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("`create_time` >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`create_time` >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("`create_time` <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`create_time` <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("`create_time` in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("`create_time` not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("`create_time` between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`create_time` not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("`create_user` is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("`create_user` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("`create_user` =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("`create_user` <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("`create_user` >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("`create_user` >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("`create_user` <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("`create_user` <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("`create_user` like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("`create_user` not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("`create_user` in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("`create_user` not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("`create_user` between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("`create_user` not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIsNull() {
            addCriterion("`last_modify_time` is null");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIsNotNull() {
            addCriterion("`last_modify_time` is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeEqualTo(Date value) {
            addCriterion("`last_modify_time` =", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotEqualTo(Date value) {
            addCriterion("`last_modify_time` <>", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeGreaterThan(Date value) {
            addCriterion("`last_modify_time` >", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`last_modify_time` >=", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeLessThan(Date value) {
            addCriterion("`last_modify_time` <", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("`last_modify_time` <=", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIn(List<Date> values) {
            addCriterion("`last_modify_time` in", values, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotIn(List<Date> values) {
            addCriterion("`last_modify_time` not in", values, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeBetween(Date value1, Date value2) {
            addCriterion("`last_modify_time` between", value1, value2, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("`last_modify_time` not between", value1, value2, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIsNull() {
            addCriterion("`last_modify_user` is null");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIsNotNull() {
            addCriterion("`last_modify_user` is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserEqualTo(String value) {
            addCriterion("`last_modify_user` =", value, "lastModifyUser");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserNotEqualTo(String value) {
            addCriterion("`last_modify_user` <>", value, "lastModifyUser");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserGreaterThan(String value) {
            addCriterion("`last_modify_user` >", value, "lastModifyUser");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserGreaterThanOrEqualTo(String value) {
            addCriterion("`last_modify_user` >=", value, "lastModifyUser");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserLessThan(String value) {
            addCriterion("`last_modify_user` <", value, "lastModifyUser");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserLessThanOrEqualTo(String value) {
            addCriterion("`last_modify_user` <=", value, "lastModifyUser");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserLike(String value) {
            addCriterion("`last_modify_user` like", value, "lastModifyUser");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserNotLike(String value) {
            addCriterion("`last_modify_user` not like", value, "lastModifyUser");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIn(List<String> values) {
            addCriterion("`last_modify_user` in", values, "lastModifyUser");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserNotIn(List<String> values) {
            addCriterion("`last_modify_user` not in", values, "lastModifyUser");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserBetween(String value1, String value2) {
            addCriterion("`last_modify_user` between", value1, value2, "lastModifyUser");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserNotBetween(String value1, String value2) {
            addCriterion("`last_modify_user` not between", value1, value2, "lastModifyUser");
            return (Criteria) this;
        }

        public Criteria andIsPrivateIsNull() {
            addCriterion("`is_private` is null");
            return (Criteria) this;
        }

        public Criteria andIsPrivateIsNotNull() {
            addCriterion("`is_private` is not null");
            return (Criteria) this;
        }

        public Criteria andIsPrivateEqualTo(Boolean value) {
            addCriterion("`is_private` =", value, "isPrivate");
            return (Criteria) this;
        }

        public Criteria andIsPrivateNotEqualTo(Boolean value) {
            addCriterion("`is_private` <>", value, "isPrivate");
            return (Criteria) this;
        }

        public Criteria andIsPrivateGreaterThan(Boolean value) {
            addCriterion("`is_private` >", value, "isPrivate");
            return (Criteria) this;
        }

        public Criteria andIsPrivateGreaterThanOrEqualTo(Boolean value) {
            addCriterion("`is_private` >=", value, "isPrivate");
            return (Criteria) this;
        }

        public Criteria andIsPrivateLessThan(Boolean value) {
            addCriterion("`is_private` <", value, "isPrivate");
            return (Criteria) this;
        }

        public Criteria andIsPrivateLessThanOrEqualTo(Boolean value) {
            addCriterion("`is_private` <=", value, "isPrivate");
            return (Criteria) this;
        }

        public Criteria andIsPrivateIn(List<Boolean> values) {
            addCriterion("`is_private` in", values, "isPrivate");
            return (Criteria) this;
        }

        public Criteria andIsPrivateNotIn(List<Boolean> values) {
            addCriterion("`is_private` not in", values, "isPrivate");
            return (Criteria) this;
        }

        public Criteria andIsPrivateBetween(Boolean value1, Boolean value2) {
            addCriterion("`is_private` between", value1, value2, "isPrivate");
            return (Criteria) this;
        }

        public Criteria andIsPrivateNotBetween(Boolean value1, Boolean value2) {
            addCriterion("`is_private` not between", value1, value2, "isPrivate");
            return (Criteria) this;
        }

        public Criteria andMaxRankIsNull() {
            addCriterion("`max_rank` is null");
            return (Criteria) this;
        }

        public Criteria andMaxRankIsNotNull() {
            addCriterion("`max_rank` is not null");
            return (Criteria) this;
        }

        public Criteria andMaxRankEqualTo(String value) {
            addCriterion("`max_rank` =", value, "maxRank");
            return (Criteria) this;
        }

        public Criteria andMaxRankNotEqualTo(String value) {
            addCriterion("`max_rank` <>", value, "maxRank");
            return (Criteria) this;
        }

        public Criteria andMaxRankGreaterThan(String value) {
            addCriterion("`max_rank` >", value, "maxRank");
            return (Criteria) this;
        }

        public Criteria andMaxRankGreaterThanOrEqualTo(String value) {
            addCriterion("`max_rank` >=", value, "maxRank");
            return (Criteria) this;
        }

        public Criteria andMaxRankLessThan(String value) {
            addCriterion("`max_rank` <", value, "maxRank");
            return (Criteria) this;
        }

        public Criteria andMaxRankLessThanOrEqualTo(String value) {
            addCriterion("`max_rank` <=", value, "maxRank");
            return (Criteria) this;
        }

        public Criteria andMaxRankLike(String value) {
            addCriterion("`max_rank` like", value, "maxRank");
            return (Criteria) this;
        }

        public Criteria andMaxRankNotLike(String value) {
            addCriterion("`max_rank` not like", value, "maxRank");
            return (Criteria) this;
        }

        public Criteria andMaxRankIn(List<String> values) {
            addCriterion("`max_rank` in", values, "maxRank");
            return (Criteria) this;
        }

        public Criteria andMaxRankNotIn(List<String> values) {
            addCriterion("`max_rank` not in", values, "maxRank");
            return (Criteria) this;
        }

        public Criteria andMaxRankBetween(String value1, String value2) {
            addCriterion("`max_rank` between", value1, value2, "maxRank");
            return (Criteria) this;
        }

        public Criteria andMaxRankNotBetween(String value1, String value2) {
            addCriterion("`max_rank` not between", value1, value2, "maxRank");
            return (Criteria) this;
        }

        public Criteria andKeepDaysIsNull() {
            addCriterion("`keep_days` is null");
            return (Criteria) this;
        }

        public Criteria andKeepDaysIsNotNull() {
            addCriterion("`keep_days` is not null");
            return (Criteria) this;
        }

        public Criteria andKeepDaysEqualTo(Long value) {
            addCriterion("`keep_days` =", value, "keepDays");
            return (Criteria) this;
        }

        public Criteria andKeepDaysNotEqualTo(Long value) {
            addCriterion("`keep_days` <>", value, "keepDays");
            return (Criteria) this;
        }

        public Criteria andKeepDaysGreaterThan(Long value) {
            addCriterion("`keep_days` >", value, "keepDays");
            return (Criteria) this;
        }

        public Criteria andKeepDaysGreaterThanOrEqualTo(Long value) {
            addCriterion("`keep_days` >=", value, "keepDays");
            return (Criteria) this;
        }

        public Criteria andKeepDaysLessThan(Long value) {
            addCriterion("`keep_days` <", value, "keepDays");
            return (Criteria) this;
        }

        public Criteria andKeepDaysLessThanOrEqualTo(Long value) {
            addCriterion("`keep_days` <=", value, "keepDays");
            return (Criteria) this;
        }

        public Criteria andKeepDaysIn(List<Long> values) {
            addCriterion("`keep_days` in", values, "keepDays");
            return (Criteria) this;
        }

        public Criteria andKeepDaysNotIn(List<Long> values) {
            addCriterion("`keep_days` not in", values, "keepDays");
            return (Criteria) this;
        }

        public Criteria andKeepDaysBetween(Long value1, Long value2) {
            addCriterion("`keep_days` between", value1, value2, "keepDays");
            return (Criteria) this;
        }

        public Criteria andKeepDaysNotBetween(Long value1, Long value2) {
            addCriterion("`keep_days` not between", value1, value2, "keepDays");
            return (Criteria) this;
        }

        public Criteria andPlanKeepDaysIsNull() {
            addCriterion("`plan_keep_days` is null");
            return (Criteria) this;
        }

        public Criteria andPlanKeepDaysIsNotNull() {
            addCriterion("`plan_keep_days` is not null");
            return (Criteria) this;
        }

        public Criteria andPlanKeepDaysEqualTo(Long value) {
            addCriterion("`plan_keep_days` =", value, "planKeepDays");
            return (Criteria) this;
        }

        public Criteria andPlanKeepDaysNotEqualTo(Long value) {
            addCriterion("`plan_keep_days` <>", value, "planKeepDays");
            return (Criteria) this;
        }

        public Criteria andPlanKeepDaysGreaterThan(Long value) {
            addCriterion("`plan_keep_days` >", value, "planKeepDays");
            return (Criteria) this;
        }

        public Criteria andPlanKeepDaysGreaterThanOrEqualTo(Long value) {
            addCriterion("`plan_keep_days` >=", value, "planKeepDays");
            return (Criteria) this;
        }

        public Criteria andPlanKeepDaysLessThan(Long value) {
            addCriterion("`plan_keep_days` <", value, "planKeepDays");
            return (Criteria) this;
        }

        public Criteria andPlanKeepDaysLessThanOrEqualTo(Long value) {
            addCriterion("`plan_keep_days` <=", value, "planKeepDays");
            return (Criteria) this;
        }

        public Criteria andPlanKeepDaysIn(List<Long> values) {
            addCriterion("`plan_keep_days` in", values, "planKeepDays");
            return (Criteria) this;
        }

        public Criteria andPlanKeepDaysNotIn(List<Long> values) {
            addCriterion("`plan_keep_days` not in", values, "planKeepDays");
            return (Criteria) this;
        }

        public Criteria andPlanKeepDaysBetween(Long value1, Long value2) {
            addCriterion("`plan_keep_days` between", value1, value2, "planKeepDays");
            return (Criteria) this;
        }

        public Criteria andPlanKeepDaysNotBetween(Long value1, Long value2) {
            addCriterion("`plan_keep_days` not between", value1, value2, "planKeepDays");
            return (Criteria) this;
        }

        public Criteria andTopScoreIsNull() {
            addCriterion("`top_score` is null");
            return (Criteria) this;
        }

        public Criteria andTopScoreIsNotNull() {
            addCriterion("`top_score` is not null");
            return (Criteria) this;
        }

        public Criteria andTopScoreEqualTo(Long value) {
            addCriterion("`top_score` =", value, "topScore");
            return (Criteria) this;
        }

        public Criteria andTopScoreNotEqualTo(Long value) {
            addCriterion("`top_score` <>", value, "topScore");
            return (Criteria) this;
        }

        public Criteria andTopScoreGreaterThan(Long value) {
            addCriterion("`top_score` >", value, "topScore");
            return (Criteria) this;
        }

        public Criteria andTopScoreGreaterThanOrEqualTo(Long value) {
            addCriterion("`top_score` >=", value, "topScore");
            return (Criteria) this;
        }

        public Criteria andTopScoreLessThan(Long value) {
            addCriterion("`top_score` <", value, "topScore");
            return (Criteria) this;
        }

        public Criteria andTopScoreLessThanOrEqualTo(Long value) {
            addCriterion("`top_score` <=", value, "topScore");
            return (Criteria) this;
        }

        public Criteria andTopScoreIn(List<Long> values) {
            addCriterion("`top_score` in", values, "topScore");
            return (Criteria) this;
        }

        public Criteria andTopScoreNotIn(List<Long> values) {
            addCriterion("`top_score` not in", values, "topScore");
            return (Criteria) this;
        }

        public Criteria andTopScoreBetween(Long value1, Long value2) {
            addCriterion("`top_score` between", value1, value2, "topScore");
            return (Criteria) this;
        }

        public Criteria andTopScoreNotBetween(Long value1, Long value2) {
            addCriterion("`top_score` not between", value1, value2, "topScore");
            return (Criteria) this;
        }

        public Criteria andIsStrictIsNull() {
            addCriterion("`is_strict` is null");
            return (Criteria) this;
        }

        public Criteria andIsStrictIsNotNull() {
            addCriterion("`is_strict` is not null");
            return (Criteria) this;
        }

        public Criteria andIsStrictEqualTo(Boolean value) {
            addCriterion("`is_strict` =", value, "isStrict");
            return (Criteria) this;
        }

        public Criteria andIsStrictNotEqualTo(Boolean value) {
            addCriterion("`is_strict` <>", value, "isStrict");
            return (Criteria) this;
        }

        public Criteria andIsStrictGreaterThan(Boolean value) {
            addCriterion("`is_strict` >", value, "isStrict");
            return (Criteria) this;
        }

        public Criteria andIsStrictGreaterThanOrEqualTo(Boolean value) {
            addCriterion("`is_strict` >=", value, "isStrict");
            return (Criteria) this;
        }

        public Criteria andIsStrictLessThan(Boolean value) {
            addCriterion("`is_strict` <", value, "isStrict");
            return (Criteria) this;
        }

        public Criteria andIsStrictLessThanOrEqualTo(Boolean value) {
            addCriterion("`is_strict` <=", value, "isStrict");
            return (Criteria) this;
        }

        public Criteria andIsStrictIn(List<Boolean> values) {
            addCriterion("`is_strict` in", values, "isStrict");
            return (Criteria) this;
        }

        public Criteria andIsStrictNotIn(List<Boolean> values) {
            addCriterion("`is_strict` not in", values, "isStrict");
            return (Criteria) this;
        }

        public Criteria andIsStrictBetween(Boolean value1, Boolean value2) {
            addCriterion("`is_strict` between", value1, value2, "isStrict");
            return (Criteria) this;
        }

        public Criteria andIsStrictNotBetween(Boolean value1, Boolean value2) {
            addCriterion("`is_strict` not between", value1, value2, "isStrict");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("`start_time` is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("`start_time` is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("`start_time` =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("`start_time` <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("`start_time` >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`start_time` >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("`start_time` <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("`start_time` <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("`start_time` in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("`start_time` not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("`start_time` between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("`start_time` not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("`end_time` is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("`end_time` is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("`end_time` =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("`end_time` <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("`end_time` >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`end_time` >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("`end_time` <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("`end_time` <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("`end_time` in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("`end_time` not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("`end_time` between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("`end_time` not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andIsActiveIsNull() {
            addCriterion("`is_active` is null");
            return (Criteria) this;
        }

        public Criteria andIsActiveIsNotNull() {
            addCriterion("`is_active` is not null");
            return (Criteria) this;
        }

        public Criteria andIsActiveEqualTo(Boolean value) {
            addCriterion("`is_active` =", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveNotEqualTo(Boolean value) {
            addCriterion("`is_active` <>", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveGreaterThan(Boolean value) {
            addCriterion("`is_active` >", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveGreaterThanOrEqualTo(Boolean value) {
            addCriterion("`is_active` >=", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveLessThan(Boolean value) {
            addCriterion("`is_active` <", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveLessThanOrEqualTo(Boolean value) {
            addCriterion("`is_active` <=", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveIn(List<Boolean> values) {
            addCriterion("`is_active` in", values, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveNotIn(List<Boolean> values) {
            addCriterion("`is_active` not in", values, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveBetween(Boolean value1, Boolean value2) {
            addCriterion("`is_active` between", value1, value2, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveNotBetween(Boolean value1, Boolean value2) {
            addCriterion("`is_active` not between", value1, value2, "isActive");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project
     * @Author mybatis-code-generator
     *
     * @mbg.generated do_not_delete_during_merge Fri Feb 10 17:22:46 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project
     * @Author mybatis-code-generator
     *
     * @mbg.generated Fri Feb 10 17:22:46 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}