apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "es.fullname" . }}
  labels:
    {{- include "es.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "es.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "es.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "es.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: kfs-pvc
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
        {{- if .Values.esConfig }}
        - name: esconfig
          configMap:
            name: es-config
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: kfs-pvc
              subPath: es/data
            - mountPath: /usr/share/elasticsearch/backup
              name: kfs-pvc
              subPath: es/backup
            - mountPath: /usr/share/elasticsearch/logs
              name: kfs-pvc
              subPath: es/logs
            {{- range $path, $config := .Values.esConfig }}
            - name: esconfig
              mountPath: /usr/share/elasticsearch/config/{{ $path }}
              subPath: {{ $path }}
            {{- end }}
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "{{ .Values.esJavaOpts }}"
          ports:
            - name: http
              containerPort: 9200
              protocol: TCP
            - name: tcp
              containerPort: 9300
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 120
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
            failureThreshold: 3
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
            failureThreshold: 3
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  strategy:
    type: Recreate