apiVersion: v1
kind: PersistentVolume
metadata:
    name: kfs-pv
spec:
  storageClassName: "kfs"
  capacity:
      storage: 1Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=3
  nfs:
    path: /cfs-4skezunfj5
    server: 10.1.0.119