apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: kfs-pvc
spec:
  storageClassName: "kfs"
  volumeName: kfs-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti