app:
  env: offline
  endpoint:
    format: https://%s.ezone-i.work
server:
  port: 8501
logging:
  level: TRACE
db:
  url: jdbc:mysql://10.5.0.10:3306/ezproject_internal?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
  username: ezproject_i_w
  password: iR2sTkrnemmyBDnE
es:
  uris:
    - http://es:9200
  username:
  password:
redis:
  address: redis://10.5.0.20:6379
  db: 4
mq:
  address: 10.5.2.2:9876
sso:
  endpoint: https://ezone-i.work/v1/ezbase/iam
  interceptor:
    exclude:
      pattern: /monitor/**;/project/api/**;/swagger/**;/project/company/**
ezadmin:
  endpoint: http://10.5.2.3:9101
  interceptor:
    pattern: /project/company/**
relativeEzbaseStorage:
  rootPath: ezproject/storage
storage:
  selector: fileStorage
  fileStorage:
    rootPath: /app/storage
internal:
  api:
    token: 123456
  eztest:
    endpoint: http://eztest:8788
    token: 123456
  ezcode:
    endpoint: http://10.5.2.3:8101
    token: 123456
  ezdeploy:
    endpoint: http://10.5.2.3:8401
    token: 123456
  ezpipeline:
    endpoint: http://10.5.2.3:8201
    token: 123456
  ezwiki:
    endpoint: http://ezwiki:9001
    token: 123456
  ezpkg:
    endpoint: http://10.5.2.193:8388
    token: 123456
  ezdoc:
    endpoint: https://ezone-i.work/v1/ezdoc
    token: 123456
  ezk8s:
    endpoint: http://10.5.2.3:8452
    token: 123456
  ezbpm:
    endpoint: https://ezone-i.work/v1/ezbase/bpm
    token: 123456
dailyIncrLimit:
  company:
    project: -1
    portfolio: -1
  project:
    card: -1
project:
  defaultConfig:
    planKeepDays: 365
