apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.pv.name }}
spec:
  storageClassName: "kfs"
  volumeName: {{ .Values.pv.name }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti